Added 2-6 tasks of DataStructure
PKholodniuk/DataStructure pull request #1
Opened 2024-11-28 21:33 UTC by PKholodniuk

2024-11-30 09:03 UTC, Delvin09 requested changes

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/BinaryTreeSearch.cs
> +            public int Value { get; set; }
сеттер зайвий

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/BinaryTreeSearch.cs
> +        public int Count { get; set; }
сеттери повинні бути private

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/BinaryTreeSearch.cs
> +            array[index] = node.Value;
```
            index = AddToArray(node.Left, array, index);

            array[index] = node.Value;
            index++;

            index = AddToArray(node.Right, array, index);
```

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +            public object Data { get; set; }
сеттер зайвий

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +        public int Count { get; set; } = 0;
сеттер приватний

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +        public Node? First { get; set; }
властивості First та Last повинні повертати значення, а не ноди

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +                Node? current = First;
навіщо? можна же Last.Next = new Node(data); Last = Last.Next;

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +            if (Count >= 1)
Не зовсім зроміл навіщо. Краще зробити через while як у тебе було у Add

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +            if (index >= 0 && index <= Count)
інвертуй перевірку

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +            if (index >= 0 && index <= Count)
не впевненний що index може дорівнювати Count

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +                    for (int i = 0; i <= Count; i++)
Не можу зрозуміти чому індекс порівнюється з порядковим номером

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +                        if (index - i == 1)
```
public void Insert(object? data, int index)
{
    if (index < 0 || index >= Count) throw new IndexOutOfRangeException();

    if (index == 0)
    {
        AddFirst(data);
    }
    else
    {
        Node? current = First;
        Node? previos = null;
        for (int i = 0; i < index && current != null; i++, current = current.Next)
        {
            previos = current;
        }

        if (previos != null)
        {
            var newNode = new Node(data, current);
            previos.Next = newNode;

            Count++;
        }
    }
}
```

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SpecialQueue.cs
> +        public int Count { get; set; } = 0;
сеттер приватний

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SpecialQueue.cs
> +        public int Count { get; set; } = 0;
і взагалі його значення можно брати з внутряшнього листа

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/SpecialStak.cs
> +        public int Count { get; set; } = 0;
Такіж самі зауваження як і для черги

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/DoublyLinkedList.cs
> +            public object Data { get; set; }
сеттер тут не треба

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/DoublyLinkedList.cs
> +        public int Count { get; set; } = 0;
такіж зауваження як і до однозвязного листа

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/DoublyLinkedList.cs
> +                Node? current = First;
var newNode = new Node(data, prev: Last, next: null);
Last.Next = newNode;
Last = newNode;

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/DoublyLinkedList.cs
> +            if (Count == 1)
var newNode = new Node(data, prev: null, next: First);
First.Prev = newNode;
First = newNode;

навіщо ще переверяти каунт на 1???

2024-11-30 09:03 UTC, Delvin09 commented on DataStructureLib/DoublyLinkedList.cs
> +            if (index >= 0 && index <= Count)
дивись коментарь у однозвязному, тільки трохи по іншому буде створення та звязка:

```
var newNode = new Node(data, next: current, prev: previos);
previos.Next = newNode;
current.Prev = newNode;
```

2024-12-01 12:19 UTC, PKholodniuk commented on DataStructureLib/BinaryTreeSearch.cs
> +            public int Value { get; set; }
> сеттер зайвий

done

2024-12-01 12:20 UTC, PKholodniuk commented on DataStructureLib/BinaryTreeSearch.cs
> +        public int Count { get; set; }
done

2024-12-01 12:20 UTC, PKholodniuk commented on DataStructureLib/BinaryTreeSearch.cs
> +        public int Count { get; set; }
> сеттери повинні бути private

done

2024-12-01 12:24 UTC, PKholodniuk commented on DataStructureLib/BinaryTreeSearch.cs
> +            array[index] = node.Value;
> ```
>             index = AddToArray(node.Left, array, index);
> 
>             array[index] = node.Value;
>             index++;
> 
>             index = AddToArray(node.Right, array, index);
> ```

трішки не так, спочатку присваюється індекс 0 із рута ( 90 строка AddToArray(Root, array, 0);), а потому ліва чи права
![image](https://github.com/user-attachments/assets/583d5ee1-5dd1-420b-8bbb-e05a58876abc)

2024-12-01 12:26 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +            public object Data { get; set; }
> сеттер зайвий

done

2024-12-01 12:26 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +        public int Count { get; set; } = 0;
> сеттер приватний

done

2024-12-01 12:30 UTC, PKholodniuk commented on DataStructureLib/DoublyLinkedList.cs
> +            public object Data { get; set; }
> сеттер тут не треба

done

2024-12-01 12:30 UTC, PKholodniuk commented on DataStructureLib/DoublyLinkedList.cs
> +        public int Count { get; set; } = 0;
> такіж зауваження як і до однозвязного листа

done

2024-12-01 14:07 UTC, PKholodniuk commented on DataStructureLib/DoublyLinkedList.cs
> +                Node? current = First;
запропонований код не працює

2024-12-01 14:10 UTC, PKholodniuk commented on DataStructureLib/DoublyLinkedList.cs
> +            if (Count == 1)
> var newNode = new Node(data, prev: null, next: First); First.Prev = newNode; First = newNode;
> 
> навіщо ще переверяти каунт на 1???

тому що ласт прівіус залишається нал

2024-12-01 14:14 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +                Node? current = First;
запропонований код не працює

2024-12-01 14:22 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +            if (Count >= 1)
> Не зовсім зроміл навіщо. Краще зробити через while як у тебе було у Add

можна по різному, але тоді потрібно окрему перевірку на ласт, так як ласт.некст дорівнює нал і цикл вийде не перевіривши Ласт

2024-12-01 14:24 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +            if (index >= 0 && index <= Count)
> не впевненний що index може дорівнювати Count

зробив так щоб інсерт працював із додаванням в кінець масиву, тобто працював як ед ласт, у випадку індекса == Каунт (умов реалізації не було тому вирішив так)

2024-12-01 14:26 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +                    for (int i = 0; i <= Count; i++)
> Не можу зрозуміти чому індекс порівнюється з порядковим номером

зробив так щоб інсерт працював із додаванням в кінець масиву, тобто працював як ед ласт, у випадку індекса == Каунт (умов реалізації не було, тому вирішив)

2024-12-01 14:34 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +                        if (index - i == 1)
> ```
> public void Insert(object? data, int index)
> {
>     if (index < 0 || index >= Count) throw new IndexOutOfRangeException();
> 
>     if (index == 0)
>     {
>         AddFirst(data);
>     }
>     else
>     {
>         Node? current = First;
>         Node? previos = null;
>         for (int i = 0; i < index && current != null; i++, current = current.Next)
>         {
>             previos = current;
>         }
> 
>         if (previos != null)
>         {
>             var newNode = new Node(data, current);
>             previos.Next = newNode;
> 
>             Count++;
>         }
>     }
> }
> ```

done

2024-12-01 14:37 UTC, PKholodniuk commented on DataStructureLib/SpecialQueue.cs
> +        public int Count { get; set; } = 0;
> сеттер приватний

done

2024-12-01 14:38 UTC, PKholodniuk commented on DataStructureLib/SpecialStak.cs
> +        public int Count { get; set; } = 0;
> Такіж самі зауваження як і для черги

done

2024-12-01 14:44 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +        public Node? First { get; set; }
> властивості First та Last повинні повертати значення, а не ноди

в умовах немає що має повертати інт, тому як написав так і є, і коли повертає ноди то як раз і важче було методи писати і методи тому іноді дивні 
![image](https://github.com/user-attachments/assets/e5994554-5b6d-4604-a664-6a7600c1b289)

2024-12-01 14:47 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +        public Node? First { get; set; }
в загальному так, якщо Ви були би замовник, то прийшлось би міняти властивості, але оскільки ми тут вчимося то мабуть так можна залишити

2024-12-01 14:48 UTC, PKholodniuk commented on DataStructureLib/DoublyLinkedList.cs
> +            if (index >= 0 && index <= Count)
в першому вже відповів чому так

2024-12-01 17:42 UTC, Delvin09 commented on DataStructureLib/BinaryTreeSearch.cs
> +            array[index] = node.Value;
розберемо на занятті. Але треба щоб був упорядкованний масив

2024-12-01 17:43 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +        public Node? First { get; set; }
не хотів би щоб ноди були публічними, але ок

2024-12-01 18:03 UTC, Delvin09 requested changes

2024-12-01 18:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +                Node? current = First;
а чому на додання в кінець валяться тести до інсерта в середену?

2024-12-01 18:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +                Node? current = First;
ідея додання нового значення в кінець дуже проста, не треба перебирати всі елементи, якщо знаєшь про останній

2024-12-01 18:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +                Node? current = First;
спробуй подебажити

2024-12-01 18:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +            if (index >= 0 && index <= Count)
у нас для цого повинен викликатися Add

2024-12-01 18:03 UTC, Delvin09 commented on DataStructureLib/DoublyLinkedList.cs
> +            if (Count == 1)
Тоді у тебе Last та First однакові
у цьому немає сенсу:
``Last.Previous = current;
First.Previous = current;``
тобто можна зробити тількі щось одна (наприклад `First.Previous = current`)

тоді код не буде відрізнятися від того що в else

2024-12-01 18:03 UTC, Delvin09 commented on DataStructureLib/DoublyLinkedList.cs
> +                Node? current = First;
чому?

2024-12-01 18:03 UTC, Delvin09 commented on DataStructureLib/SinglyLinkedList.cs
> +            if (Count >= 1)
```
var currentNode = First;
while (currentNode != null)
{

currentNode = currentNode.Next;
}
```

або

```
for(var currentNode = First; currentNode != null; currentNode = currentNode.Next)
{}

```

просто тобі тут Count не потрібен.

2024-12-01 21:43 UTC, PKholodniuk commented on DataStructureLib/BinaryTreeSearch.cs
> +            array[index] = node.Value;
> розберемо на занятті. Але треба щоб був упорядкованний масив

а я зараз в тупіку, як можна обєкти упорядкувати :(

2024-12-01 22:06 UTC, PKholodniuk commented on DataStructureLib/DoublyLinkedList.cs
> +            if (Count == 1)
> Тоді у тебе Last та First однакові у цьому немає сенсу: `Last.Previous = current; First.Previous = current;` тобто можна зробити тількі щось одна (наприклад `First.Previous = current`)
> 
> тоді код не буде відрізнятися від того що в else

це дійсно щось пробував і залишилось, бо в початковому варіанті його не було 
![image](https://github.com/user-attachments/assets/5df99193-c190-498d-bb03-506a2d5b9ea7)

2024-12-01 22:10 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +            if (index >= 0 && index <= Count)
> у нас для цого повинен викликатися Add

дан в попередніх змінах

2024-12-01 22:23 UTC, PKholodniuk commented on DataStructureLib/SinglyLinkedList.cs
> +                Node? current = First;
> а чому на додання в кінець валяться тести до інсерта в середену?

мабуть тести трішки не правильно називаються або не правильна логіка тестів, в тих тестах міксоване наповнення листа, різними методами адд та інсерт, якщо адд валиться то валиться в усіх тестах де він використовувався, то цікаво як тестовий підхід то правильно мікси використовувати, але як юніт тетси, то мабуть не правильно

2024-12-01 22:28 UTC, PKholodniuk commented on DataStructureLib/DoublyLinkedList.cs
> +            if (Count == 1)
> Тоді у тебе Last та First однакові у цьому немає сенсу: `Last.Previous = current; First.Previous = current;` тобто можна зробити тількі щось одна (наприклад `First.Previous = current`)
> 
> тоді код не буде відрізнятися від того що в else

2024-12-01 22:29 UTC, merged